# Generated by Django 3.1.6 on 2021-08-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=50)),
                ('movie_review', models.CharField(max_length=50)),
                ('movie_release_date', models.CharField(max_length=50)),
                ('movie_detail', models.TextField(max_length=500)),
                ('movie_hero', models.CharField(max_length=50)),
                ('movie_heroin', models.CharField(max_length=50)),
            ],
        ),
    ]
